---
storagePath: "~/spinozacoin/blockchain"
port: 8888
# type:  wallet, minimal_node, full, node_history, account_history, transaction_history, node_and_account_history, node_and_transactions_history, account_and_transactions_history
type: "full"
trustedAccountHistory: "127.0.0.1"
trustedNodeHistory: "127.0.0.1"
trustedTransactionHistory: "127.0.0.1"
# each will listen on port + i (with i = 0, 1, 2, ..., instances-1)
instances: 1000
# percent or count
countIgnoringBroadcast: 300
# logging.CRITICAL=50|logging.ERROR=40|logging.WARNING=30|logging.INFO=20|logging.DEBUG=10|logging.NOTSET=0
loggingLevel: 10
